cp -f /home/user/git_projects/redis-unstable/redis/src/adlist.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/adlist.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/ae.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/ae_epoll.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/ae_evport.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/ae.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/ae_kqueue.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/ae_select.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/anet.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/anet.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/config.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/crc64.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/dict.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/dict.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/endianconv.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/endianconv.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/lzf_c.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/lzf_d.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/lzf.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/lzfP.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/pqsort.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/pqsort.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/rand.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/rand.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/sds.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/sds.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/sha1.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/sha1.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/sync.sh .
cp -f /home/user/git_projects/redis-unstable/redis/src/util.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/util.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/ziplist.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/ziplist.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/zipmap.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/zipmap.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/zmalloc.c .
cp -f /home/user/git_projects/redis-unstable/redis/src/zmalloc.h .
cp -f /home/user/git_projects/redis-unstable/redis/src/fmacros.h .
